# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/hmcts/cpp-hooks-pre-commit-terraform
    rev: main
    hooks:
      - id: terraform_fmt
        verbose: true
      - id: terraform_validate
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
          - --hook-config=--path-to-file=README.md
  - repo: https://github.com/hmcts/cpp-hooks-gitleaks
    rev: main
    hooks:
      - id: gitleaks
